Feature: Templates für Pull Requests
McNamara84/ELMO-EPOS-Laboratory-Metadata-Optimizer pull request #365
Opened 2024-12-22 05:22 UTC by McNamara84

2024-12-25 09:54 UTC, Ali-GeoFZ commented
Wie kann ich die Änderungen im Branch testen😅?

ich hatte die Idee, einen neuen Branch von diesem Branch zu erstellen und dann eine Pull Request einzureichen, um das neue Tempelte zu nutzen, aber das hat leider nicht funktioniert.

2024-12-25 10:38 UTC, McNamara84 commented
> Wie kann ich die Änderungen im Branch testen😅?
> 
> ich hatte die Idee, einen neuen Branch von diesem Branch zu erstellen und dann eine Pull Request einzureichen, um das neue Tempelte zu nutzen, aber das hat leider nicht funktioniert.

Da musst du schon der Dokumentation [hier auf GitHub](https://docs.github.com/de/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) vertrauen und die beiden Vorlagen sichten.
So richtig testen kann man das dann erst, wenn die beiden Vorlagen in Main sind, wenn ich das richtig verstanden habe, denn Pull Requests erstellst du ja dann im von main aus gesehen.

2024-12-30 07:36 UTC, Ali-GeoFZ requested changes
Danke für den Pull Request! Die Vorlagen sehen sehr gut aus.


Zur ".github/PULL_REQUEST_REVIEW_TEMPLATE.md"

Beim Punkt "Sicherheit" schlag ich vor, statt einem Checklist-Punkt ein offenes Eingabefeld zu verwenden. um genauer zu wissen welche potenzielle Sicherheitsrisiken dort berücksichtigt wurden.

Dies ermöglicht uns, detailliert und spezifisch auf die Sicherheitsmaßnahmen einzugehen, die für die jeweilige Implementierung relevant sind.




zur ".github/PULL_REQUEST_TEMPLATE.md"

Ich schlag vor, einen Abschnitt "Anmerkung" hinzuzufügen, um es Ersteller:in zu ermöglichen zusätzliche Informationen oder Gedanken zu den Änderungen bereitzustellen.

So könnte es aussehen:

## Anmerkung(Note)
[Hier können Sie zusätzliche Informationen, Erklärungen oder Gedanken zu den Änderungen hinzufügen.]

und 
## Checklist
Ich habe sicher gestellt, dass die Änderungen den Barrierefreiheitsrichtlinien entsprechen. "Um es zu vermeiden, jedes mal Barrierefreiheitsteste durchzuführen :)".  Der Punkt find ich wichtig.



Sonst sieht alles ausgezeichnet aus! Danke für deine tolle Arbeit!

2024-12-30 09:23 UTC, jaFHP commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] Meine Änderungen erzeugen keine neuen Warnungen
Warnungen wo?

2024-12-30 09:25 UTC, jaFHP commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] Neue und bestehende Unit-Tests bestehen lokal
"bestehen lokal" heißt "sie werden lokal bestanden"? bestehen ist hier unglücklich doppeldeutig... ich denk nochmal drüber nach wie man das verständlicher formulieren kann...

2024-12-30 09:25 UTC, jaFHP commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] Neue und bestehende automatische Unit-Tests bestehen im Pull Request
auch hier "bestehen" disambiguierten

2024-12-30 09:55 UTC, McNamara84 commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] Meine Änderungen erzeugen keine neuen Warnungen
> Warnungen wo?

In der Konsole deines Test-Browsers.

2024-12-30 10:01 UTC, jaFHP commented
Ich würde schon gerne noch die Anpassung von Selenium-Tests mit aufnehmen. zumindest, dass sie lokal durchlaufen. Seid ihr damit einverstanden?

2024-12-30 10:03 UTC, McNamara84 commented
> Ich würde schon gerne noch die Anpassung von Selenium-Tests mit aufnehmen. zumindest, dass sie lokal durchlaufen. Seid ihr damit einverstanden?

Asche auf mein Haupt - die habe ich tatsächlich einfach vergessen.

2024-12-30 10:16 UTC, jaFHP approved these changes
von mir aus jetztapproved. Danke für die hilfreiche Vorlage!

2024-12-30 13:15 UTC, Ali-GeoFZ approved these changes
Ich hab auch jetzt meine Vorschläge selbst gemacht und approved. Falls ihr damit nicht einverstanden seit gerne schreiben oder selbst bearbeiten :)!

2024-12-30 13:18 UTC, Ali-GeoFZ commented
> Anmerkung(Note)
[Hier können Sie zusätzliche Informationen, Erklärungen oder Gedanken zu den Änderungen hinzufügen.]

Ich verzichte auf diesen Punkt, da ich ihn nicht als besonders wichtig sehe.

2024-12-30 16:21 UTC, merged