Feature: Sortierbare Autoren
McNamara84/ELMO-EPOS-Laboratory-Metadata-Optimizer pull request #366
Opened 2024-12-23 04:38 UTC by McNamara84

2024-12-30 08:23 UTC, Ali-GeoFZ requested changes
_**Danke für deine schöne Implementierung!**_

Ich habe die Funktionalität getestet und möchte auf folgendes Problem hinweisen:
Wenn die Hauptzeile nach unten verschoben und dann eine neue Zeile geklont wird, funktionieren der Autocomplete und der Remove-Button in der neuen Zeile nicht. Wenn die Hauptzeile jedoch zurück an ihre ursprüngliche Position verschoben und dann geklont wird, funktionieren sowohl Autocomplete als auch der Remove-Button wie erwartet.

2024-12-30 16:31 UTC, McNamara84 commented
> _**Danke für deine schöne Implementierung!**_
> 
> Ich habe die Funktionalität getestet und möchte auf folgendes Problem hinweisen: Wenn die Hauptzeile nach unten verschoben und dann eine neue Zeile geklont wird, funktionieren der Autocomplete und der Remove-Button in der neuen Zeile nicht. Wenn die Hauptzeile jedoch zurück an ihre ursprüngliche Position verschoben und dann geklont wird, funktionieren sowohl Autocomplete als auch der Remove-Button wie erwartet.

Danke für das Feedback. Scheint so als müsste ich die Tagify-Instanz ondrag entfernen und ondrop wieder instanziieren. Wird schnellstmöglich korrigiert. Guter Hinweis. Danke!

2024-12-30 17:36 UTC, McNamara84 commented
@jaFHP , ich hab dich jetzt auch mal für die Review angefragt. Deine Kritik im Daily am UI würde ich gerne umsetzen, benötige dafür aber einen konkreten Verbesserungsvorschlag um klarer ersichtlich zu machen, dass das der Darg Handle ist. Mouseover könnte ich mir vorstellen, aber für mehr fehlt mir aktuell die Phantasie...

2024-12-31 10:19 UTC, jaFHP requested changes
Funktionalitäten find ich super. Speichern und xml-Genrerierung funktioniert immer in der richtigen Reihenfolge. 
Das Symbol scheint ein drag&drop Symbol zu sein, ich kannte es nur nicht... wie findest du dieses hier? Das ist zumindest in meinem Kopf verständlicher.
![grafik](https://github.com/user-attachments/assets/1feb1a75-cc7e-4b47-9ed7-8d94968b4bf0)

Vielleicht würde ein Tooltip an dieser Stelle noch helfen? Also, beim Mouseover dem Symbol: "drag&drop to change order" oder so?

2024-12-31 11:32 UTC, Ali-GeoFZ approved these changes
Die Autocomplete-Funktion und der Remove-Button in der geklonten Zeile arbeiten nun wie gewünscht. Dankr für deine Mühe! approved!

2025-01-02 08:27 UTC, jaFHP approved these changes
Danke! Approved

2025-01-02 08:33 UTC, merged