Feature: Link to imprint
McNamara84/ELMO-EPOS-Laboratory-Metadata-Optimizer pull request #369
Opened 2024-12-28 04:48 UTC by McNamara84

Fixed #259

2024-12-30 16:30 UTC, jaFHP requested changes
"Das Impressum wird häufig mit der falschen Übersetzung „Imprint“ übersetzt. Die korrekte Übersetzung lautet hingegen entweder „Legal Notice“ oder „Legal Disclosure“." (sagt e-recht24) 
Ich würde mich da mal am EU Parlament orientieren und das Ganze **Legal notice** nennen.

Warum hast du den Changelog für Version 1.7 gelöscht?

2024-12-30 17:44 UTC, McNamara84 commented
> Warum hast du den Changelog für Version 1.7 gelöscht?

Wollten wir in diesem Modal nicht lediglich die letzten drei Versionen aufführen? Wer ältere Versionsunterschiede anschauen möchte, kann ja dann im Zweifelsfall hier im repository reinschauen und wird schlauer.

2024-12-31 09:56 UTC, jaFHP commented
> > Warum hast du den Changelog für Version 1.7 gelöscht?
> 
> Wollten wir in diesem Modal nicht lediglich die letzten drei Versionen aufführen? Wer ältere Versionsunterschiede anschauen möchte, kann ja dann im Zweifelsfall hier im repository reinschauen und wird schlauer.

An die Absprache kann ich mich ehrlich gesagt nicht erinnern. Finde das "rauslöschen" unnötig. Mehr Info ist besser als weniger, finde ich :)

2024-12-31 10:00 UTC, jaFHP approved these changes
Approved! auch wenn ich den Changelog lieber vollständig lassen würde :)

2024-12-31 10:13 UTC, McNamara84 commented
> Approved! auch wenn ich den Changelog lieber vollständig lassen würde :)

Danke! Ich baue ihn wieder ein und merge dann selbständig.

2024-12-31 10:44 UTC, merged